clear
Import-Module D:\GitHub\ProductivityTools.PSPublishModuleToPowershellGallery\ProductivityTools.PSPublishModuleToPowershellGallery\ProductivityTools.PSPublishModuleToPowershellGallery.psm1 -Force
cd D:\GitHub\ProductivityTools.PSPublishModuleToPowerShellGallery\

Publish-ModuleToPowerShellGallery -Verbose -IncreaseModuleVersion 