clear
Import-Module D:\GitHub\ProductivityTools.PSPublishModuleToPowershellGallery\ProductivityTools.PSPublishModuleToPowershellGallery\ProductivityTools.PSPublishModuleToPowershellGallery.psm1 -Force
cd D:\GitHub\ProductivityTools.PSPublishModuleToPowershellGallery\ProductivityTools.PSPublishModuleToPowershellGallery
Set-MasterConfigurationBaseConfigurationFile -BaseConfigurationFileName D:\Tech\PSMasterConfiguration.xml
Publish-ModuleToPowershellGallery -Verbose